### ISSUE TITLE
The WebSocket transport is not available when enable sms sniffer

### ISSUE THREAD

**Issue by Jhinxs** [sharyer/gsmevil2#15]
The WebSocket transport is not available, you must install a WebSocket server that is compatible with your async mode to enable it. See the documentation for details. (further occurrences of this error will be logged with level INFO)
sms sniffer started
Traceback (most recent call last):
  File "gsmevil.py", line 285, in <module>
    GsmSniffer.sniffer()
  File "gsmevil.py", line 45, in sniffer
    capture = pyshark.LiveCapture(interface='lo', bpf_filter='port 4729 and not icmp and udp')
  File "/usr/local/lib/python3.8/dist-packages/pyshark/capture/live_capture.py", line 58, in __init__
    all_interfaces = get_tshark_interfaces(tshark_path)
  File "/usr/local/lib/python3.8/dist-packages/pyshark/tshark/tshark.py", line 112, in get_tshark_interfaces
    parameters = [get_process_path(tshark_path), "-D"]
  File "/usr/local/lib/python3.8/dist-packages/pyshark/tshark/tshark.py", line 70, in get_process_path
    raise TSharkNotFoundException(
pyshark.tshark.tshark.TSharkNotFoundException: TShark not found. Try adding its location to the configuration file. Searched these paths: ['C:\\Program Files\\Wireshark\\tshark.exe', '/usr/local/sbin/tshark', '/usr/local/bin/tshark', '/usr/sbin/tshark', '/usr/bin/tshark', '/sbin/tshark', '/bin/tshark', '/snap/bin/tshark']

**Comment by core-c** [comment]
In your **/usr/local/lib/python3.8/dist-packages/pyshark** there is a file named **config.ini**.
You need to edit that file so that **tshark_path** has a proper value.
I pointed it to my tshark.py
