### ISSUE TITLE
gsmevil2 installation issue with 

### ISSUE THREAD

**Issue by supashot** [sharyer/gsmevil2#4]
according to the description I have to install pip3 install pyshark flask flask_socketio logging sqlite3 but logging included in base install of python3.

I got some GSM traffic, checked I could get some IMSI with https://github.com/Oros42/IMSI-catcher

I can launch gsmevil2 and connect to the web interface no traffic ieven activting to sms and imsi options, maybe due to the failed installation of logging module.
Trying to install sudo pip3 install logging will generate this error:
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qj3pjs03/logging/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qj3pjs03/logging/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-qj3pjs03/logging/pip-egg-info                                                      
         cwd: /tmp/pip-install-qj3pjs03/logging/                                                                                                                
    Complete output (48 lines):                                                                                                                                 
    running egg_info                                                                                                                                            
    creating /tmp/pip-install-qj3pjs03/logging/pip-egg-info/logging.egg-info                                                                                    
    writing /tmp/pip-install-qj3pjs03/logging/pip-egg-info/logging.egg-info/PKG-INFO                                                                            
    writing dependency_links to /tmp/pip-install-qj3pjs03/logging/pip-egg-info/logging.egg-info/dependency_links.txt                                            
    writing top-level names to /tmp/pip-install-qj3pjs03/logging/pip-egg-info/logging.egg-info/top_level.txt                                                    
    writing manifest file '/tmp/pip-install-qj3pjs03/logging/pip-egg-info/logging.egg-info/SOURCES.txt'                                                         
    Traceback (most recent call last):                                                                                                                          
      File "<string>", line 1, in <module>                                                                                                                      
      File "/tmp/pip-install-qj3pjs03/logging/setup.py", line 3, in <module>                                                                                    
        setup(name = "logging",                                                                                                                                 
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup                                                                                           
        dist.run_commands()                                                                                                                                     
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands                                                                                    
        self.run_command(cmd)                                                                                                                                   
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command                                                                                     
        cmd_obj.run()                                                                                                                                           
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 297, in run                                                                    
        self.find_sources()                                                                                                                                     
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 304, in find_sources                                                           
        mm.run()                                                                                                                                                
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 535, in run                                                                    
        self.add_defaults()                                                                                                                                     
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 571, in add_defaults                                                           
        sdist.add_defaults(self)                                                                                                                                
      File "/usr/lib/python3.8/distutils/command/sdist.py", line 226, in add_defaults                                                                           
        self._add_defaults_python()                                                                                                                             
      File "/usr/lib/python3/dist-packages/setuptools/command/sdist.py", line 135, in _add_defaults_python                                                      
        build_py = self.get_finalized_command('build_py')                                                                                                       
      File "/usr/lib/python3.8/distutils/cmd.py", line 298, in get_finalized_command                                                                            
        cmd_obj = self.distribution.get_command_obj(command, create)                                                                                            
      File "/usr/lib/python3.8/distutils/dist.py", line 857, in get_command_obj                                                                                 
        klass = self.get_command_class(command)                                                                                                                 
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 764, in get_command_class                                                                  
        self.cmdclass[command] = cmdclass = ep.load()                                                                                                           
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2450, in load                                                                       
        return self.resolve()                                                                                                                                   
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2456, in resolve                                                                    
        module = __import__(self.module_name, fromlist=['__name__'], level=0)                                                                                   
      File "/usr/lib/python3/dist-packages/setuptools/command/build_py.py", line 16, in <module>                                                                
        from setuptools.lib2to3_ex import Mixin2to3                                                                                                             
      File "/usr/lib/python3/dist-packages/setuptools/lib2to3_ex.py", line 12, in <module>                                                                      
        from lib2to3.refactor import RefactoringTool, get_fixers_from_package                                                                                   
      File "/usr/lib/python3.8/lib2to3/refactor.py", line 19, in <module>                                                                                       
        import logging                                                                                                                                          
      File "/tmp/pip-install-qj3pjs03/logging/logging/__init__.py", line 618                                                                                    
        raise NotImplementedError, 'emit must be implemented '\                                                                                                 
                                 ^                                                                                                                              
    SyntaxError: invalid syntax                                                                                                                                 
    ----------------------------------------                                                                                                                    
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Any idea?

**Comment by sharyer** [comment]
if you facing issue in installing any package that's not gsmevil issue.

**Comment by supashot** [comment]
Yes it's an issue in your installation description because part of python3 core.

**Comment by sharyer** [comment]
can you share more info about your issue like any error at gsmevil2 running..
